name: Train Model On-Premise

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: self-hosted  # Usa el runner local que configuraste

    steps:
      - name: Run training
        run: python train.py

      - name: Run Prediction
        run: python predict.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            model.pkl
            feature_importance.png
            predictions.csv
