name: CI for ML Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run training
        run: python train.py

      - name: Run prediction
        run: python predict.py

      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

      - name: Upload feature importance plot
        uses: actions/upload-artifact@v4
        with:
          name: feature-importance
          path: feature_importance.png

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: predictions.csv